src/MibSBilevel.cpp, src/MibSCutGenerator.cpp, src/MibSModel.cpp
Some problems found in checkBilevelFeasibility()
- L525: when entering the UB solving block, the corresponding parameter `isLinkVarsIntegral_` to `computeBestUBWhenLVarsInt` was missing; this reflects the mibs paper, where the parameter was also not included (for some unknown reason?) But I think it is still necessary...
- L652: this condition will check if `(x, \hat{y})`  is bilevel feasible and mark it as a heuristic solution; the tag here is changed to explicitly `LowerIsFeasible` because the old one includes `NotSet` case, and if linking solution pool is not used, the condition will always be satisfied. The case `LowerIsInfeasible` is already filtered at `!shouldPrune_`.
- L540 & L604 (not included in this (1st) commit as I am still thinking about a good way to rearrange):  these are …
=> Miscellaneous bug fixes for stable/1.2

src/MibSModel.cpp, src/MibSModel.hpp, src/MibSParams.cpp, src/MibSParams.hpp
Added a function to write LL/SL/second stage problem into an auxiliary file; number style follows standard .mps format;
Will add/change 
- a MibS parameter for the writing option;
- the path/name of the file as a parameter;
- readAuxiliaryData() offer options to read LL/SL variables by name instead of indices?
=> Add function to write aux file

src/MibSModel.cpp
This commit
- added new keywords used in the name-based .aux file format;
- read SL/LL information including row name + index, column name + index, objective sense + coefficients;
- no change to the interdiction reading system.
=> update MibSModel::readAuxiliaryData to include name-based file format

src/MibSModel.cpp, src/MibSModel.hpp
The equality constraints are handled at the beginning of `MibSModel::loadProblemData()`, after reading the `MPS` and `AUX` files, before further data loading. Then, `MibSModel` only recognizes the problem after parsing equality constraints. This is different from the original plan described in Slack as I was trying to place all the iterations in one block. 
Added variables: `inputLowerRowInd_`,  `inputLowerRowNum_` to track the original data from input files; they are necessary if writeAuxData is called.
Change in the output: printed information from `mps` functions will show the original row numbers, and those from `MibS` analyzing data will reflect the split row numbers.
=> Add code to handle equality constraints

src/MibSModel.cpp
Modify the equality constraint code block to handle other range constraints. Tested using linderoth.txt by adding 
`RANGES
RHS       R0000004  20. ` 
or 
`RANGES
RHS       R0000000  20. ` 
to the original problem. The `lpSolver.writeLp()` output matched the modifications. 
No change to writing functions, as they are either handled by `mps->writeMps` or already covered in the equality constraint commits.
=> Read range constraints

src/MibSModel.cpp
Fixed some minor bugs. No (substantive) changes to read/write functions.
1. removed a redundant condition check for equality/range constraints (though I think C++ is using a short circuit logic so it may not be that redundant?);
2. added `break` to `findIndex()` so it terminates once the target is found;
3. added comments for reference.
=> Read range constraints (continue): remove redundant condition check and fix bugs

src/MibSModel.cpp
In MibSModel::loadProblemData(), if the lower level matrix is empty, add y_0 <= UB_(y_0) as a trivial row.
=> add parser to handle empty LL/SL matrix

src/MibSSolution.cpp
Following up on #115  : fix the problem that some information was displayed twice when printing solutions to a file.
=> avoid printing the same information to std::out twice

src/MibSCutGenerator.cpp, src/MibSCutGenerator.hpp
Caused by unbounded \llv\ variables.
- If the bigM problem is determined unbounded or does not have an optimal solution, set the value of bigM to `-inf`.
- Add a boolean variable `isBigMIncObjErr_` to track this case, and turn off Benders binary cut once the error is detected.
Will run more tests.
=> skip the generation of Benders binary cut if the bigM problem is unbounded

src/MibSBilevel.cpp
In the function `setUpModel()' in MibSBilevel:
- remove the rounding on the original row bounds `b^2`;
- add a tolerance check before rounding values `b^2 - A^2 x`.
=> Change the row bound rounding rule to tolerance based when set up the LL/SL problem

src/MibSBilevel.cpp, src/MibSCutGenerator.cpp, src/MibSCutGenerator.hpp, src/MibSModel.cpp, src/MibSModel.hpp, src/MibSTreeNode.cpp
MibS feasibility check would label current node as should be pruned if timeout happens during solving the lower-level/second-stage problem. The terminating log will output the best lower bound as if the latest node is not yet processed.
Changes:
- Added a boolean variable in `MibSModel` as a flag once the preset time limit is reached during the feasibility check in `MibSBilevel`.
- In `MibSCutGenerator`, add the same exit flag when timeout during generating various intersection cuts.
- In `MibSTreeNode`, mark the most recent node exploration as "partially processed", so the termination process will keep the node knowledge instead of removing it.
=> Fix the node pruning logic when the time limit is reached

src/MibSBilevel.cpp, src/MibSCutGenerator.cpp, src/MibSModel.cpp, src/MibSModel.hpp
- Variable name change: `sizeFixedInd` to `sizeLinkVars` to match a earlier name change.
- Update iterations for finding the linking variables to upper-level/first-stage only.
- In `MibSModel`, move the "check linking variables are integers" block from `readProblemData()` to `analyzeStructure()`; it also fix a bug on indices.
=> update linking related variable name and replace some binarySearch

src/MibSModel.cpp
When IDIC parameter is not set, add a condition in the check to make sure that the cut cannot be turned on if some of the lower objective coefficients are not integers.
=> Fix a bug when setting up the improving direction intersection cut

src/MibSCutGenerator.cpp
When dealing with problems featuring lower-level coefficients with a large number of significant digits, the cut generation problem for IDIC might yield an all-zero "optimal" solution that is infeasible due to numerical issues.
- In the future, we may consider checking the greatest common divisor of the coefficients in the lower-level objective function and rescaling them before solving the problem?
=> skip IDIC if the generation problem returns infeasible solution

.github/workflows/linux-ci.yml, .github/workflows/windows-ci.yml
This PR adds only the remaining changes to CI already made in MibS for outdated actions.
Notaby:
- Always upload artifact
- Windows: Replace --enable-msvc=MD with --enable-msvc
- Linux: Add macos-14 arm64
- Linux: Use latest package name generation for macos
- Note: Without Windows MSVS steps
=> Remaining update ci for macos-14, enable-msvc, uploading build artifacts [stable/1.2]

.github/workflows/linux-ci.yml, .github/workflows/windows-ci.yml
- Update outdated build actions
- Always upload artifact
- Windows: Remove mingw32 builds
- Linux: Replace macos-12 with 13 (and fix gcc build issues)
- Linux: Add macos-14 arm64
- Linux: Use latest package name generation for macos
- Note: Without Windows MSVS steps
NOTE: This PR does NOT harmonize "--disable-shared": Most workflows use the same "ADD_BUILD_ARGS+=( --static --with-lapack='-llapack -lblas -lgfortran -lquadmath -lm' )", but MibS and SYMPHONY use "ADD_BUILD_ARGS+=( --disable-shared )". See [discussion](https://github.com/coin-or/COIN-OR-OptimizationSuite/issues/25#issuecomment-1995707199)
=> Update CI for outdated actions, build issues, add macos-14, remove mingw32 [master]

src/MibSModel.cpp, src/MibSParams.cpp
In MibSModel::printProblemInfo(), change the default Improving Solution Intersection Cut message to Type I cut.
=> Change default ISIC message to (Type I)

.github/workflows/windows-ci.yml
See [COIN-OR-OptimizationSuite Issue 30](https://github.com/coin-or/COIN-OR-OptimizationSuite/issues/30): Windows-CI for stables create "-md.zip" binaries that are really "MT"
=> Fix windows-ci for stable to build MSVC with dynamically linked runtime

src/MibSModel.cpp
To fix the bug in #134: since `loadProblemData()` expects a column-oriented data matrix, we consider adding a check to the beginning of the function and creating a reversed copy if a row-oriented matrix is detected.
=> Check input matrix orientation when loading problem data

src/MibSCutGenerator.cpp
This PR fixed a bug in [a previous change](https://github.com/coin-or/MibS/pull/131#issue-2019981938) #131  that skipped the generation of an improving direction intersection cut when the generation problem returned an all-zero solution.
The new line determines the all-zero solution using the defined tolerance instead of zero.
=> skip IDIC if the generation problem returns infeasible solution - follow up

.github/workflows/linux-ci.yml, .github/workflows/windows-ci.yml
See also COIN-OR-OptimizationSuite [Issue 32](https://github.com/coin-or/COIN-OR-OptimizationSuite/issues/32) and [Issue 33](https://github.com/coin-or/COIN-OR-OptimizationSuite/issues/33):
1. Remove Windows Server 2019 runner images for Actions are being deprecated in June 2025.
1. Add tests for the new Windows Server 2025 which was released Nov 2024.
1. Similarly, remove deprecated Ubuntu 20.04 and add new Ubuntu 24.04
These changes are done for linux-ci, windows-ci (using coinbrew) and windows-msvs-ci (using Visual Studio solutions) workflows.
=> Update ci for windows and linux for deprecated and new OS
